version: "3.6"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  api:
    build: ./backend
    environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - PORT=${WEB_PORT_HTTP}
  web:
    build: ./client
    environment:
      - WEB_PORT=${WEB_PORT_HTTP}
      - DOMAIN_NAME=${DOMAIN_NAME}
  caddy:
    build: ./caddy
    command: caddy run
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./caddy/web:/app"
      - caddy_data:/data
    environment:
      - WEB_PORT=${WEB_PORT}
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${WEB_PORT_HTTP}:80"
    depends_on:
      - api
      - web

volumes:
  postgres_data: { }
  caddy_data: { }

